using System;
using System.Linq;
using FsCheck;
using NUnit.Framework;
using UnityEngine;

// Feature: light-puzzle-game, Property 10: Level validation correctness
// Validates: Requirements 6.1, 7.1, 7.2, 7.4

[TestFixture]
public class LevelValidationTests
{
    // Property 10a: Valid levels generated by LevelDataArbitrary are always accepted
    [Test]
    public void ValidLevels_AreAcceptedByValidation()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, level =>
        {
            var result = LevelValidator.Validate(level);
            Assert.IsTrue(result.IsValid,
                $"Valid level rejected. Errors: {string.Join("; ", result.Errors)}");
        }).QuickCheckThrowOnFailure();
    }

    // Property 10b: Levels with invalid tile values are rejected
    [Test]
    public void Levels_WithInvalidTileValues_AreRejected()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, Arb.From(Gen.Choose(0, 7).Select(i => new[] { "X", ".", "W", "0", " ", "##", "?", "1" }[i])),
            (level, badTile) =>
        {
            // Find an interior floor tile and replace it with an invalid value
            for (int y = 1; y < level.height - 1; y++)
            {
                for (int x = 1; x < level.width - 1; x++)
                {
                    if (level.tiles[y].row[x] == "_")
                    {
                        // Make sure this tile isn't used by player start or any object
                        if (level.playerStart.x == x && level.playerStart.y == y) continue;
                        if (level.beamEmitters.Any(b => b.x == x && b.y == y)) continue;
                        if (level.puzzleObjectives.Any(p => p.x == x && p.y == y)) continue;
                        if (level.lightSources.Any(l => l.x == x && l.y == y)) continue;
                        if (level.mirrors != null && level.mirrors.Any(m => m.x == x && m.y == y)) continue;

                        level.tiles[y].row[x] = badTile;
                        var result = LevelValidator.Validate(level);
                        Assert.IsFalse(result.IsValid, $"Level with invalid tile '{badTile}' was accepted");
                        return;
                    }
                }
            }
            // If no free floor tile found, skip this case (still valid)
        }).QuickCheckThrowOnFailure();
    }

    // Property 10c: Levels with no beam emitters are rejected
    [Test]
    public void Levels_WithNoBeamEmitters_AreRejected()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, level =>
        {
            level.beamEmitters = new BeamEmitterData[0];
            var result = LevelValidator.Validate(level);
            Assert.IsFalse(result.IsValid, "Level with no beam emitters was accepted");
            Assert.IsTrue(result.Errors.Any(e => e.Contains("beam emitter")),
                "Error should mention beam emitter");
        }).QuickCheckThrowOnFailure();
    }

    // Property 10d: Levels with no puzzle objectives are rejected
    [Test]
    public void Levels_WithNoPuzzleObjectives_AreRejected()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, level =>
        {
            level.puzzleObjectives = new PositionData[0];
            var result = LevelValidator.Validate(level);
            Assert.IsFalse(result.IsValid, "Level with no puzzle objectives was accepted");
            Assert.IsTrue(result.Errors.Any(e => e.Contains("puzzle objective")),
                "Error should mention puzzle objective");
        }).QuickCheckThrowOnFailure();
    }

    // Property 10e: Levels with player start on a wall tile are rejected
    [Test]
    public void Levels_WithPlayerStartOnWall_AreRejected()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, level =>
        {
            // Place player start on a wall (border is always wall)
            level.playerStart = new PositionData { x = 0, y = 0 };
            var result = LevelValidator.Validate(level);
            Assert.IsFalse(result.IsValid, "Level with player on wall was accepted");
        }).QuickCheckThrowOnFailure();
    }

    // Property 10f: Levels with out-of-bounds object positions are rejected
    [Test]
    public void Levels_WithOutOfBoundsPositions_AreRejected()
    {
        var arb = LevelDataArbitrary.Generate();

        Prop.ForAll(arb, level =>
        {
            // Move player start out of bounds
            level.playerStart = new PositionData { x = level.width + 5, y = level.height + 5 };
            var result = LevelValidator.Validate(level);
            Assert.IsFalse(result.IsValid, "Level with out-of-bounds player start was accepted");
            Assert.IsTrue(result.Errors.Any(e => e.Contains("out of bounds")),
                "Error should mention out of bounds");
        }).QuickCheckThrowOnFailure();
    }
}
